include "renderer.fbs";
namespace novus.editor;

table EditorPipelineInfo
{
    pipeline: renderer.GraphicsPipeline;
    vertex_shader_path: string;
    fragment_shader_path: string;
}

table EditorSceneInfo
{
    name:string;
    path: string;
    resources: [string];
}

table EditorMeshInfo
{
    mesh: renderer.Mesh;
    model_path: string;
}

table EditorMaterialInfo
{

}

table EditorRenderPassInfo
{
    subpasses: [renderer.Renderpass];
}

table EditorModelInfo
{

}

table EditorDrawCommandInfo
{
    draw_command: renderer.DrawCommand;
}

table EditorComputeCommandInfo
{

}