include "renderer.fbs";
namespace novus.editor;


table EditorPipelineInfo
{
    pipeline: renderer.GraphicsPipeline;
    vertex_shader_path: string;
    fragment_shader_path: string;
    samplers: [internal.ShaderSampler] (native_inline);
}



table EditorMeshInfo
{
    mesh: renderer.Mesh;
    model_path: string;
}
table EditorMaterialTextureInfo
{
    path: string;
    attachment_name: string; //when using framebuffer
    framebuffer_name: string;
    sampler_name: string;
    model_texture_type: internal.ModelTextureType;
}
table EditorMaterialInfo
{
    name:string;
    textures: [EditorMaterialTextureInfo] (native_inline);
    pipeline_path: string;
}

table EditorSubpassInfo
{
    command_paths: [string];
    framebuffer_path: string;
    framebuffer_index: int32;
}

table EditorRenderPassInfo
{
    subpass_infos: [EditorSubpassInfo] (native_inline);
}

table EditorModelInfo
{

}

table EditorDrawCommandInfo
{
    draw_command: renderer.DrawCommand;
    material_path: string;
    mesh_path: string;
}

table EditorComputeCommandInfo
{

}

table EditorSceneInfo
{
    name:string;
    path: string;
    resources: [string];
    renderpass_path: string;
    system_paths: [string];
}