include "internal_renderer.fbs";
namespace novus.renderer;

table Shader
{
    path: string;
    info: internal.ShaderInfo (native_inline);
}
table GraphicsPipeline
{
    vertex_shader_index: int32 = -1;
    fragment_shader_index: int32 = -1;
    compute_shader_index: int32 = -1;
    name: string;
    info: internal.GraphicsPipelineInfo;
}

table Material
{
    name:string;
    pipeline_index: int32 = -1;
}
enum MeshPrimitiveType : byte
{
        QUAD = 0,
        CUBE = 1,
        SPHERE = 2,
        MODEL = 3,
        NONE = 4,
}
table Mesh
{
     mesh_name: string;
     model_index: int32;
     primitive_type: MeshPrimitiveType;
}
enum DrawMode : byte
{
    TRIANGLES=0,
    TRIANGLE_STRIP=1
}
table DrawCommand
{
    name: string;
    material_index: int32 = -1;
    mesh_index: int32 = -1;
    count: int32;
    mode: DrawMode;
    draw_elements: bool;
    automatic_draw: bool;
}

struct Dependency
{
    subpass_index: int32;
}

table Subpass
{
    info: internal.RenderPassInfo;
    commands: [DrawCommand] (native_inline);
    name: string;
}

table Renderpass
{
    sub_passes: [Subpass] (native_inline);
}

table Texture
{

}

table Framebuffer
{

}

table Scene
{
    name:string;
    shaders: [Shader] (native_inline);
    pipelines: [GraphicsPipeline](native_inline);
    render_pass: Renderpass;
    meshes: [Mesh] (native_inline);
    materials: [Material] (native_inline);
}