include "internal_renderer.fbs";
include "engine.fbs";
namespace novus.renderer;

table Shader
{
    path: string;
    num_samplers: uint32;
    num_storage_textures: uint32;
    uniform_buffers: [internal.BufferAttribute] (native_inline);
    types: [internal.BufferStruct] (native_inline);
    storage_buffers: [internal.BufferAttribute] (native_inline);
    shader_stage: internal.ShaderStage;
}
table GraphicsPipeline
{
    vertex_shader_index: int32 = -1;
    fragment_shader_index: int32 = -1;
    compute_shader_index: int32 = -1;
    name: string;
    info: internal.GraphicsPipelineInfo;
}

table StorageBufferBinding
{
    buffer_name: string;
    binding: int32;
    shader_stage : internal.ShaderStage;
}

table Material
{
    name:string;
    pipeline_index: int32 = -1;
    storage_buffer_bindings: [StorageBufferBinding] (native_inline);
}
enum MeshPrimitiveType : byte
{
        QUAD = 0,
        CUBE = 1,
        SPHERE = 2,
        MODEL = 3,
        NONE = 4,
}
table Mesh
{
     mesh_name: string;
     model_index: int32;
     primitive_type: MeshPrimitiveType;
}
enum DrawMode : byte
{
    TRIANGLES=0,
    TRIANGLE_STRIP=1
}
table DrawCommand
{
    name: string;
    material_index: int32 = -1;
    mesh_index: int32 = -1;
    count: int32;
    mode: DrawMode;
    draw_elements: bool;
    automatic_draw: bool;
}

struct Dependency
{
    subpass_index: int32;
}

table Renderpass
{
    info: internal.RenderPassInfo;
    commands: [DrawCommand] (native_inline);
    name: string;
}

table StorageBuffer
{
    name: string;
    block_size: int64;
}

table Texture
{

}

table Framebuffer
{

}

table Cubemap
{
    texture_paths: [string];
}

table Scene
{
    name:string;
    shaders: [Shader] (native_inline);
    pipelines: [GraphicsPipeline](native_inline);
    sub_passes: [Renderpass] (native_inline);
    meshes: [Mesh] (native_inline);
    materials: [Material] (native_inline);
    systems: [engine.System] (native_inline);
    buffers: [StorageBuffer] (native_inline);
}